# Generated by Django 2.2.16 on 2022-11-14 01:00

from django.db import migrations, models

import api.validators


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_auto_20221108_1446"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("user", "Пользователь"),
                    ("moderator", "Модератор"),
                    ("admin", "Администратор"),
                ],
                default="user",
                max_length=9,
                verbose_name="Роль",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                error_messages={
                    "unique": "Пользователь с таким именем уже существует!"
                },
                max_length=150,
                unique=True,
                validators=[api.validators.username_validator],
                verbose_name="Имя пользователя",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                check=models.Q(_negated=True, username="me"),
                name="name_not_me",
            ),
        ),
    ]
