# Generated by Django 2.2.16 on 2022-11-08 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0002_auto_20221108_1446"),
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="title",
            name="category",
        ),
        migrations.RemoveField(
            model_name="title",
            name="genre",
        ),
        migrations.DeleteModel(
            name="Category",
        ),
        migrations.DeleteModel(
            name="Genre",
        ),
        migrations.DeleteModel(
            name="Title",
        ),
    ]
