# Generated by Django 2.2.16 on 2022-11-10 23:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0004_auto_20221109_1107"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name="genre",
            name="name",
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name="title",
            name="name",
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name="title",
            name="year",
            field=models.PositiveSmallIntegerField(
                db_index=True,
                validators=[
                    django.core.validators.MinValueValidator(1730),
                    django.core.validators.MaxValueValidator(2022),
                ],
            ),
        ),
    ]
